version: '3'

services:

  graphene:
    depends_on:
      - coreference
    build:
      context: .
      dockerfile: graphene-server/target/classes/Dockerfile-server
    ports:
      - "8080:8080"
    links:
      - coreference
    volumes:
      - ./logs:/usr/share/graphene/logs
      - ./conf:/usr/share/graphene/conf

  coreference:
    depends_on:
      - corenlp
    image: "lambdacube/pycobalt:v1.1.1"
    environment:
      - PYCOBALT_CORENLP=http://corenlp:9000
    expose:
      - "5128"
    links:
      - corenlp


  corenlp:
    image: "lambdacube/corenlp:3.7.0"
    expose:
      - "9000"
