FROM java:jre-alpine

ADD *.jar /corenlp/

WORKDIR /corenlp

EXPOSE 9000

CMD ["java", "-mx8g", "-server", "-cp", "*", \
     "edu.stanford.nlp.pipeline.StanfordCoreNLPServer", \
     "--port", "9000", \
     "--annotators", "tokenize,ssplit,pos,lemma,ner", \
     "--preload", "tokenize,ssplit,pos,lemma,ner", \
     "--timeout", "60000"]
