# original sentence: 'The café arrived in Paris in the 17th century , when the beverage was first brought from Turkey , and by the 18th century Parisian cafés were centres of the city 's political and cultural life .'

## core sentence: 'the café arrived in Paris in the 17th century .'
DIS_TYPE:		CORE-8874b563-12ce-4e67-9f59-3b4d7f0882c1		DISCOURSE_TYPE		DISCOURSE_CORE
CORE_EXT:		CORE-8874b563-12ce-4e67-9f59-3b4d7f0882c1		the café		arrived		in Paris
RHET_REL:		CORE-8874b563-12ce-4e67-9f59-3b4d7f0882c1		JOINT_LIST		CORE-c0123203-3227-4b8f-9744-9fc1b64f4607
RHET_REL:		CORE-8874b563-12ce-4e67-9f59-3b4d7f0882c1		BACKGROUND		CORE-852b01fd-6a17-42c7-bd1a-30385b8c2acb

## core sentence: 'Parisian cafés were centres of the city 's political and cultural life .'
DIS_TYPE:		CORE-c0123203-3227-4b8f-9744-9fc1b64f4607		DISCOURSE_TYPE		DISCOURSE_CORE
CORE_EXT:		CORE-c0123203-3227-4b8f-9744-9fc1b64f4607		Parisian cafés		were		centres of the city 's political and cultural life
RHET_REL:		CORE-c0123203-3227-4b8f-9744-9fc1b64f4607		JOINT_LIST		CORE-8874b563-12ce-4e67-9f59-3b4d7f0882c1
### context sentence: 'This was by the 18th century .'
CONT_EXT:		CONTEXT-343e1c2a-f6be-45ca-a9f2-55b0d9eb2d8a		This		was		by the 18th century
RHET_REL:		CORE-c0123203-3227-4b8f-9744-9fc1b64f4607		UNKNOWN_SENT_SIM		CONTEXT-343e1c2a-f6be-45ca-a9f2-55b0d9eb2d8a

## core sentence: 'the beverage was first brought .'
DIS_TYPE:		CORE-852b01fd-6a17-42c7-bd1a-30385b8c2acb		DISCOURSE_TYPE		DISCOURSE_CONTEXT
CORE_EXT:		CORE-852b01fd-6a17-42c7-bd1a-30385b8c2acb		the beverage		was brought		null
### context sentence: 'This was from Turkey .'
CONT_EXT:		CONTEXT-2aec8b1c-9d48-478c-bfdc-ab5031378137		This		was		from Turkey
RHET_REL:		CORE-852b01fd-6a17-42c7-bd1a-30385b8c2acb		LOCATION		CONTEXT-2aec8b1c-9d48-478c-bfdc-ab5031378137