# original sentence: 'Obama represented the 13th District for three terms in the Illinois Senate from 1997 to 2004 , when Obama ran for the U.S. Senate .'

## core sentence: 'Obama represented the 13th District for three terms .'
DIS_TYPE:		CORE-b020408a-fbef-404b-aa94-6162335b7293		DISCOURSE_TYPE		DISCOURSE_CORE
CORE_EXT:		CORE-b020408a-fbef-404b-aa94-6162335b7293		Obama		represented		the 13th District
RHET_REL:		CORE-b020408a-fbef-404b-aa94-6162335b7293		BACKGROUND		CORE-394524e8-9295-48da-a4f5-635ff4b6898f
### context sentence: 'This was from 1997 to 2004 .'
CONT_EXT:		CONTEXT-d977a0e9-da87-4131-9bd2-5d238cc551a5		This		was		from 1997 to 2004
RHET_REL:		CORE-b020408a-fbef-404b-aa94-6162335b7293		UNKNOWN_SENT_SIM		CONTEXT-d977a0e9-da87-4131-9bd2-5d238cc551a5
### context sentence: 'This was in the Illinois Senate .'
CONT_EXT:		CONTEXT-f824c0d5-bd9b-4c04-9a03-3c30bec716ee		This		was		in the Illinois Senate
RHET_REL:		CORE-b020408a-fbef-404b-aa94-6162335b7293		UNKNOWN_SENT_SIM		CONTEXT-f824c0d5-bd9b-4c04-9a03-3c30bec716ee

## core sentence: 'Obama ran .'
DIS_TYPE:		CORE-394524e8-9295-48da-a4f5-635ff4b6898f		DISCOURSE_TYPE		DISCOURSE_CONTEXT
CORE_EXT:		CORE-394524e8-9295-48da-a4f5-635ff4b6898f		Obama		ran		null
### context sentence: 'This was for the U.S. Senate .'
CONT_EXT:		CONTEXT-da75a548-2770-48d6-bd31-7e18d9f8477a		This		was		for the U.S. Senate
RHET_REL:		CORE-394524e8-9295-48da-a4f5-635ff4b6898f		UNKNOWN_SENT_SIM		CONTEXT-da75a548-2770-48d6-bd31-7e18d9f8477a